<template>
  <svg
    version="1.1"
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    x="0px"
    y="0px"
    width="1em"
    height="1em"
    viewBox="0 0 44 44"
    enable-background="new 0 0 0 0"
    xml:space="preserve"
  >
    <circle
      fill="#fff"
      stroke="none"
      cx="6"
      cy="22"
      r="6"
    >
      <animate
        attributeName="opacity"
        dur="1s"
        values="0;1;0"
        repeatCount="indefinite"
        begin="0.1"
      />
    </circle>
    <circle
      fill="#fff"
      stroke="none"
      cx="22"
      cy="22"
      r="6"
    >
      <animate
        attributeName="opacity"
        dur="1s"
        values="0;1;0"
        repeatCount="indefinite"
        begin="0.2"
      />
    </circle>
    <circle
      fill="#fff"
      stroke="none"
      cx="38"
      cy="22"
      r="6"
    >
      <animate
        attributeName="opacity"
        dur="1s"
        values="0;1;0"
        repeatCount="indefinite"
        begin="0.3"
      />
    </circle>
  </svg>
</template>
